import turtle

wn = turtle.Screen()
wn.bgcolor("lightblue")

tina = turtle.Turtle()
tommy = turtle.Turtle()
tina.pensize(10)
tommy.pensize(10)

tina.color('cyan')
tommy.color('green')
tina.shape('turtle')
tommy.shape('turtle')

tina.begin_fill()
tina.goto(160,0)
tina.goto(160,-200)
tina.goto(-160,-200)
tina.goto(-160,0)
tina.goto(0,0)
tina.end_fill()

tommy.penup()
tommy.goto(-70,150)
tommy.write("Tina, let's make a house together!")
tommy.goto(0,50)
tommy.pendown()

tina.penup()
tina.color('white')
tina.goto(-40,-100)
tina.write("Alright, I'm ready!!")
tina.goto(0,-130)
tina.pendown()

tommy.penup()
tommy.goto(-20,-200)
tommy.pendown()
tommy.begin_fill()
tommy.color('red')
tommy.goto(-20,-150)
tommy.goto(20,-150)
tommy.goto(20,-200)
tommy.goto(-20,-200)
tommy.end_fill()

def make_window(x=0, y=0):
    tina.penup()
    tina.color("white")
    tina.goto(x, y)
    tina.pendown()
    tina.begin_fill()
    tina.goto(x + 20, y)
    tina.goto(x + 20, y + 60)
    tina.goto(x - 20, y + 60)
    tina.goto(x - 20, y)
    tina.goto(x, y)  
    tina.end_fill()
  
make_window(-80,-80)
make_window(80,-80)

tommy.penup()
tommy.goto(-160,0)
tommy.left(45)
tommy.begin_fill()
tommy.pendown()
tommy.color("green")
tommy.goto(0,120)
tommy.goto(160,0)
tommy.goto(-160,0)
tommy.end_fill()

tina.penup()
tina.goto(-140, 160)
tina.color("black")
tina.pendown() 
for _ in range(12):
    tina.forward(50)
    tina.backward(50)
    tina.right(30)

tina.penup()
tina.goto(-140,140)
tina.color("yellow")
tina.begin_fill()
tina.circle(30)
tina.end_fill()

tina.hideturtle()
turtle.done()

tommy.hideturtle()
turtle.done()